### PR TITLE
Create Lerp.json

### PR DESCRIPTION
**Pull request by JessicaSun1022**

### CODE REVIEW

**Comment by MOXIEeee** [comment]
Everything looks good!
Only one thing to mention, can you loosen up the layout a bit so that people might be able to see each step more clearly. Most of the blocks are now crowded together and the lines cross and overlap a bit.

**Comment by JessicaSun1022** [comment]
Just cleaned it up a little. Let me know if it's still too messy.

**Comment by drwiner** [comment]
@JessicaSun1022 Looks-wise, all good. 
The "weight" is currently an integer if my start and end are integers. So I can only test with 0 or 1. It should be a decimal. 
If the input and end cannot be integers, try adding a "constraint" 
image

Thank you!

**Comment by drwiner** [comment]
Clarifying
image
When I currently submit an integer, the other inputs say they can be integer

**Comment by JessicaSun1022** [comment]
I'm not sure if I completely understand what you mean. I fixed it so that you can have a decimal input for weight now. Let me know if I missed what you wanted me to fix.

**Review by drwiner — APPROVED** [review]

**Pull request merged**
