### PR TITLE
Cosh.json

### PR DESCRIPTION
**Pull request by Inesh-volunteer**

### CODE REVIEW

**Comment by sauravpandey123** [comment]
Good job! Works as intended, but some comments:
Capitalize the first letter of every word in the composite function, according to the Graphbook template rules. So write Cosh(x). 
Also, your interface can be made cleaner. See the attached image for one example.
cosh

**Comment by Inesh-volunteer** [comment]
Yeah Muxi told us about the more straight and organized graphs, will do for
next time. Appreciate the feedback 👍

**Comment by sauravpandey123** [comment]
Thanks, please send a request when you're done with the changes :)

**Comment by Inesh-volunteer** [comment]
I made a new PR with the changes

**Pull request closed without merging**
