### PR TITLE
Create Floor Divide.json

### PR DESCRIPTION
**Pull request by JessicaSun1022**

### CODE REVIEW

**Comment by sauravpandey123** [comment]
Good job! Works, but please make your input names more descriptive.
For instance, you simply call them "input" and "other".
Better names could be divisor and dividend for example.
This will let the user know which number is dividing what.

**Comment by JessicaSun1022** [comment]
Sounds good I changed the input names.

**Comment by sauravpandey123** [comment]
Hi, could you please recheck? I still see the inputs as Input and Other.
image

**Comment by JessicaSun1022** [comment]
Interesting maybe I didn’t commit the file correctly. I’m still getting used to GitHub. Would it be okay if I just opened a new PR for Floor Divide with the revisions? If not I can try figuring out how to push a new commit within this PR it might take a little for me to figure out though as I’m fairly new to GitHub.

**Review by sauravpandey123 — APPROVED** [review]

**Pull request merged**
