### PR TITLE
Threshold.json

### PR DESCRIPTION
**Pull request by alxm101**
[Threshold.json](https://github.com/cerbrec/graphbook/files/15284738/Threshold.json)

### CODE REVIEW

**Comment by MOXIEeee** [comment]
1. Please rearrange the line from "threshold" to "target".
2. You can save the composite as operations and export it from "Saved Ops"

**Review by alxm101 — COMMENTED** [review]
Rearranged the line from "threshold" to "target"

**Comment by MOXIEeee** [comment]
1. the templates should be named as "Threshold"
2. reorganize the lines
3. In your new template, "target" input has no contribution to any ops.
4. save the template as operations and export it from "Saved Ops"

**Comment by GuoFengH1** [comment]
[Threshold.json](https://github.com/user-attachments/files/16045998/Threshold.json)
here's a fixed version as requested

**Pull request closed without merging**
