### PR TITLE
Create zeros.json

### PR DESCRIPTION
**Pull request by GuoFengH1**

### CODE REVIEW

**Comment by MOXIEeee** [comment]
Please capitalize "Z" in the name "Zeros" of the ops.

Can you do "Ones" as well, they should be almost identical, thanks a lot!

**Comment by drwiner** [comment]
If it's just a primitive, then it can be a primitive just with the "target" input already filled in.

**Comment by MOXIEeee** [comment]
I think what David means is that you don't have to create a composite but simply use the primitive "broadcast_to_shape" by changing the value of "target" and the name of the primitive.

**Comment by GuoFengH1** [comment]
Updated!

**Comment by MOXIEeee** [comment]
Ready to be merged

**Review by garrettzywang — APPROVED** [review]

**Pull request merged**
