### PR TITLE
Create RReLU.json

### PR DESCRIPTION
**Pull request by atsai2**

### CODE REVIEW

**Comment by MOXIEeee** [comment]
1. Please rename the boolean input "training?" 
2. For "Data If Training" composite, my suggestion is that you replace it with "If else" composite, which might be neater and easier to understand. You can right-click to "Create If Else", take "training" as the condition, and then "Multiply by Random" and "Multiply by Average" can be respectively arranged in "True" or "False" subgraphs.
3. After testing template output, you can clear those non-default variables, and save it as operations.

**Comment by MOXIEeee** [comment]
Please save your template as operations and export it from "Saved Ops"

**Comment by MOXIEeee** [comment]
Please save your template as operations and export it from "Saved Ops"

**Comment by MOXIEeee** [comment]
Ready to be merged.

**Review by garrettzywang — APPROVED** [review]

**Pull request merged**
